//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praduct_Pull.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallProduct
    {
        public int ID { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime DateInstall { get; set; }
        public System.DateTime DateUnistall { get; set; }
        public int QuantityLicence { get; set; }
    }
}
