//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praduct_Pull.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string NameProduck { get; set; }
        public string Version { get; set; }
        public string Type { get; set; }
        public System.DateTime DateRelease { get; set; }
        public string ApplicationArea { get; set; }
        public decimal MoneyLicence { get; set; }
    }
}
